INSERT INTO CAR_BRAND(ID, BRAND) VALUES (1, 'AUDI');
INSERT INTO CAR_BRAND(ID, BRAND) VALUES (2, 'BMW');
INSERT INTO CAR(ID, BRAND, DESCRIPTION, PRICE) VALUES (1, 1, 'Pierwsza godzina darmowa', 5.5);
INSERT INTO CAR(ID, BRAND, DESCRIPTION, PRICE) VALUES (2, 2, 'Druga godzina darmowa', 10.5);
